### ISSUE TITLE
mistakes in CO2 interpretation

### ISSUE THREAD

**Issue by adriennejune** [mlnrt/saildrone-2019-antarctica-circumnavigation#1]
Hi Matthieu.  Very nice data visualization (Saildrone Antartica Mission.pdf)!  Just wanted to bring to your attention a couple mistakes/misinterpretations of the CO2 measurements and analysis.  

First, measurement uncertainty of seawater pCO2 collected on buoys and USVs is similar to ships (0.5%; see https://doi.org/10.5194/essd-6-353-2014 and https://doi.org/10.1175/JTECH-D-20-0010.1).  The 2.8% uncertainty is associated with float-based pCO2 estimates (see http://dx.doi.org/10.1002/2016GB005541).

Second, the statement on page 6 attributed to Sutton et al. 2021 is not quite correct.  In our analysis of USV and float-based data, we suggest there is large year-to-year variability in the Southern Ocean carbon sink, with a strong sink in some years and a weaker sink in others.  Conclusions about whether or not the Southern Ocean is a strong sink need to be based on sustained, long-term observational data sets with known uncertainty, not simply one 7-month USV data set.

**Comment by mlnrt** [comment]
Thank you for taking the time to read my data visualization presentation and provide feedback. This is really much appreciated, especially as the topic is very very far away from any of my knowledge.

Regarding the first mistake you are mentioning, this is my pure ignorance because after making some research before writing this presentation, I came to the conclusion that a float was a type of buoy. I made some more research again and I have to say that in the eyes of a non-specialist like me, they look the same. But I will change it.

Regarding the second point, this is what I understood. I didn't want to write too long text and explanations as the articles and scientific papers which were released have all the details. But from your feedback, it seems my wording was not correct and I took a too short shortcut. I will fix that too.

Thank you again.

**Comment by mlnrt** [comment]
@adriennejune regarding the second point on slide 6, I was re-reading the slide and it seems we do not read it with the same nuance. Because the slide doesn't give any conclusion. It just says that the data "challenge the idea".
I'll give more thoughts on how to nicely add the information you are mentioning.

**Comment by adriennejune** [comment]
@mlnrt I agree with you that distilling science down into short communication pieces is a challenge!  You did a great job.

For the slide 6 statement, the nuance is that there is no mention of time.  The current (traditional as you say) understanding is that the Southern Ocean is a strong carbon sink **over long time periods** (~decadal).  A 7-month data set does not challenge that understanding.  The data instead suggests there is large interannual variability in that longer-term sink.  So, it is more accurate to say something like "the measures performed by the Saildrone USV highlight the significant variability in this region and challenge the idea that the Southern Ocean is always a strong carbon sink."

**Comment by mlnrt** [comment]
@adriennejune Ah, I see. Thank you for the clarification. In the mean time, I replace the buoy icon by a self-made float icon. Hopefully that is more accurate (if an icon can ever be accurate...). 
I'll work on fixing the phrasing later this week.

**Comment by mlnrt** [comment]
@adriennejune sorry it took me so long but 2022 start has been hectic. I made the correction as you proposed in the PDF presentation. I reused your proposed wording as I find it very good. Thank you again.
